'use client';

import { useEffect, useMemo, useState } from 'react';
import type { ManagerVisibilitySnapshot } from '@playbook-brain/types';
import { usePollingResource } from '@/hooks/usePollingResource';
import {
  buildManagerVisibilitySnapshot,
  getRolloutFlags,
  getRolloutPolicy,
  listManagerOpsAiDecisions,
  listManagerOpsAudit,
  listWorkflowInbox,
  mapInboxToQueueSnapshot,
} from '@/lib/p0-ui-client';
import { Badge, EmptyState, ErrorBanner, InlineButton, MetaText, P0PageShell, Panel } from './P0UiPrimitives';

export default function P0ManagerOpsPage() {
  const inbox = usePollingResource(listWorkflowInbox, {
    intervalMs: 10000,
    realtime: { path: '/workflow/realtime' },
  });
  const ai = usePollingResource(() => listManagerOpsAiDecisions(200), { intervalMs: 15000 });
  const audit = usePollingResource(() => listManagerOpsAudit(300), { intervalMs: 15000 });
  const rolloutPolicy = usePollingResource(getRolloutPolicy, { intervalMs: 30000 });
  const rolloutFlags = usePollingResource(getRolloutFlags, { intervalMs: 30000 });
  const [snapshot, setSnapshot] = useState<ManagerVisibilitySnapshot | null>(null);
  const [snapshotError, setSnapshotError] = useState<string | null>(null);
  const [snapshotLoading, setSnapshotLoading] = useState(false);

  const queueItems = useMemo(() => mapInboxToQueueSnapshot(inbox.data || []), [inbox.data]);

  useEffect(() => {
    let active = true;
    const run = async () => {
      if (inbox.error) return;
      setSnapshotLoading(true);
      setSnapshotError(null);
      try {
        const next = await buildManagerVisibilitySnapshot(queueItems, 10);
        if (!active) return;
        setSnapshot(next);
      } catch (err) {
        if (!active) return;
        setSnapshotError(err instanceof Error ? err.message : 'Failed to build manager visibility snapshot');
      } finally {
        if (active) setSnapshotLoading(false);
      }
    };
    void run();
    return () => {
      active = false;
    };
  }, [queueItems, inbox.error, ai.lastUpdatedAt, audit.lastUpdatedAt]);

  const adminError = firstAdminError([ai.error, audit.error, rolloutPolicy.error, rolloutFlags.error, snapshotError]);

  return (
    <P0PageShell
      title="Internal Validation Harness · P0 Manager Ops"
      subtitle="Temporary internal/admin validation surface for `/manager-ops/p0/*`. Not part of the primary tri-pane Cerebro operator UX."
      actions={(
        <>
          <InlineButton onClick={() => void inbox.refresh()} disabled={inbox.refreshing}>Refresh inbox source</InlineButton>
          <InlineButton onClick={() => { void ai.refresh(); void audit.refresh(); }} disabled={ai.refreshing || audit.refreshing}>Refresh trust data</InlineButton>
          <InlineButton onClick={() => { void rolloutPolicy.refresh(); void rolloutFlags.refresh(); }} disabled={rolloutPolicy.refreshing || rolloutFlags.refreshing}>Refresh rollout</InlineButton>
        </>
      )}
    >
      <Panel title="Launch Policy (Displayed, Not Mutable Here)" subtitle="UI mirrors backend constraints and avoids write affordances for read-only integrations.">
        <div className="flex flex-wrap gap-2">
          <Badge tone="info">Autotask = TWO-WAY</Badge>
          <Badge tone="warn">IT Glue = READ-ONLY</Badge>
          <Badge tone="warn">Ninja = READ-ONLY</Badge>
          <Badge tone="warn">SentinelOne = READ-ONLY</Badge>
          <Badge tone="warn">Check Point = READ-ONLY</Badge>
        </div>
      </Panel>

      {adminError ? (
        <ErrorBanner
          message={`Manager Ops data unavailable: ${adminError}`}
          hint="Current backend baseline protects `/manager-ops/*` with `requireAdmin`. UI remains visible but shows access-aware degraded state."
        />
      ) : null}

      <div className="grid gap-4 xl:grid-cols-[1.15fr_0.85fr]">
        <div className="space-y-4">
          <Panel title="Queue / SLA Visibility" subtitle="Snapshot generated by POST `/manager-ops/p0/visibility` using workflow inbox projection as queue source.">
            <div className="mb-2"><MetaText>SLA status is a P0 UI heuristic from inbox item age until live SLA feed wiring is available.</MetaText></div>
            {snapshotLoading && !snapshot ? (
              <div className="text-sm" style={{ color: 'var(--text-secondary)' }}>Building manager visibility snapshot…</div>
            ) : !snapshot ? (
              <EmptyState title="No visibility snapshot" detail="Manager ops snapshot could not be generated yet (empty inbox, access restriction, or backend unavailable)." />
            ) : (
              <QueueSlaPanel snapshot={snapshot} />
            )}
          </Panel>

          <Panel title="QA Sampling + Integrity" subtitle="P0 validation sampling and auditability integrity checks from manager-ops visibility service.">
            {!snapshot ? (
              <EmptyState title="No QA/integrity data" detail="Requires a successful `/manager-ops/p0/visibility` response." />
            ) : (
              <div className="space-y-3">
                <div className="flex flex-wrap gap-2">
                  <Badge tone={snapshot.integrity_checks.ok ? 'good' : 'warn'}>
                    Integrity {snapshot.integrity_checks.ok ? 'OK' : 'Issues'}
                  </Badge>
                  <Badge>QA sample {snapshot.qa_sampling.sample_size}</Badge>
                  <Badge tone="info">AI decisions {snapshot.ai_audit.total_decisions}</Badge>
                </div>
                <div>
                  <div className="mb-1 text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>QA Sample Tickets</div>
                  {snapshot.qa_sampling.tickets.length === 0 ? (
                    <EmptyState title="No QA samples" detail="No AI decisions mapped to current queue snapshot yet." />
                  ) : (
                    <div className="space-y-2">
                      {snapshot.qa_sampling.tickets.map((ticket) => (
                        <div key={`${ticket.ticket_id}-${ticket.reason}`} className="rounded-lg border p-2" style={{ borderColor: 'var(--border-subtle)' }}>
                          <div className="flex flex-wrap items-center gap-2">
                            <Badge tone={ticket.sla_status === 'breached' ? 'bad' : ticket.sla_status === 'at_risk' ? 'warn' : 'neutral'}>{ticket.sla_status || 'unknown'}</Badge>
                            <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>{ticket.ticket_id}</span>
                            {typeof ticket.confidence === 'number' ? <Badge tone="info">{Math.round(ticket.confidence * 100)}%</Badge> : null}
                            {ticket.hitl_status ? <Badge tone={ticket.hitl_status === 'pending' ? 'warn' : 'good'}>{ticket.hitl_status}</Badge> : null}
                          </div>
                          <div className="mt-1 text-xs" style={{ color: 'var(--text-secondary)' }}>{ticket.reason}</div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
                <div>
                  <div className="mb-1 text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>Integrity Issues</div>
                  {snapshot.integrity_checks.issues.length === 0 ? (
                    <EmptyState title="No integrity issues" detail="Cross-tenant and auditability checks passed for the snapshot inputs." />
                  ) : (
                    <ul className="space-y-1 text-sm" style={{ color: 'var(--text-secondary)' }}>
                      {snapshot.integrity_checks.issues.map((issue) => (
                        <li key={issue} className="rounded-lg border px-2 py-1" style={{ borderColor: 'rgba(240,180,41,0.2)', background: 'rgba(240,180,41,0.05)' }}>
                          {issue}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </div>
            )}
          </Panel>
        </div>

        <div className="space-y-4">
          <Panel title="AI Decision Visibility" subtitle="Live list from `/manager-ops/p0/ai-decisions`.">
            {ai.error && !/403|permissions/i.test(ai.error) ? <ErrorBanner message={`AI decisions unavailable: ${ai.error}`} /> : null}
            {(ai.data || []).length === 0 ? (
              <EmptyState title="No AI decisions" detail="No persisted trust-layer AI decisions yet for this tenant, or admin access is unavailable." />
            ) : (
              <div className="space-y-2">
                {(ai.data || []).slice(0, 12).map((d) => (
                  <div key={d.decision_id} className="rounded-lg border p-2" style={{ borderColor: 'var(--border-subtle)', background: 'rgba(255,255,255,0.015)' }}>
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone={d.hitl_status === 'pending' ? 'warn' : 'good'}>{d.hitl_status}</Badge>
                      <Badge tone="info">{Math.round(d.confidence * 100)}%</Badge>
                      <span className="text-xs font-medium" style={{ color: 'var(--text-primary)' }}>{d.ticket_id}</span>
                    </div>
                    <div className="mt-1 text-xs" style={{ color: 'var(--text-secondary)' }}>{d.suggestion.summary}</div>
                    <div className="mt-1"><MetaText>{d.decision_type} · {new Date(d.timestamp).toLocaleString()}</MetaText></div>
                  </div>
                ))}
              </div>
            )}
          </Panel>

          <Panel title="Automation / Audit Visibility" subtitle="Recent audit rows from `/manager-ops/p0/audit`, including read-only enforcement rejections.">
            {(audit.data || []).length === 0 ? (
              <EmptyState title="No audit rows" detail="Trust-layer audits appear here after AI decisions or enrichment reads/mutation rejections." />
            ) : (
              <div className="space-y-2">
                {(audit.data || []).slice(0, 12).map((row) => (
                  <div key={row.audit_id} className="rounded-lg border p-2" style={{ borderColor: 'var(--border-subtle)' }}>
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone={row.result === 'success' ? 'good' : row.result === 'rejected' ? 'warn' : 'bad'}>{row.result}</Badge>
                      <span className="text-xs font-medium" style={{ color: 'var(--text-primary)' }}>{row.action}</span>
                      {row.reason ? <Badge tone="warn">{row.reason}</Badge> : null}
                    </div>
                    <div className="mt-1"><MetaText>{new Date(row.timestamp).toLocaleString()}</MetaText></div>
                  </div>
                ))}
              </div>
            )}
          </Panel>

          <Panel title="Rollout / Admin Controls (Read-Only View)" subtitle="Optional internal rollout visibility wired because backend endpoints already exist. UI does not mutate flags in this P0 pass.">
            <div className="space-y-3 text-sm">
              <div>
                <div className="mb-1 text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>Policy</div>
                {rolloutPolicy.data ? (
                  <div className="rounded-lg border p-2" style={{ borderColor: 'var(--border-subtle)' }}>
                    <div className="flex flex-wrap gap-2">
                      <Badge tone={rolloutPolicy.data.frozen ? 'warn' : 'neutral'}>{rolloutPolicy.data.frozen ? 'Frozen policy' : 'Mutable policy'}</Badge>
                      <Badge>tenant {rolloutPolicy.data.tenant_id}</Badge>
                    </div>
                    <pre className="mt-2 overflow-auto rounded border p-2 text-xs" style={{ borderColor: 'var(--border-subtle)', background: 'rgba(0,0,0,0.25)', color: 'var(--text-secondary)' }}>
{JSON.stringify(rolloutPolicy.data.launch_policy, null, 2)}
                    </pre>
                  </div>
                ) : (
                  <EmptyState title="No rollout policy data" detail="Admin access may be unavailable or backend route returned no data." />
                )}
              </div>
              <div>
                <div className="mb-1 text-xs font-semibold uppercase tracking-wide" style={{ color: 'var(--text-muted)' }}>Flags</div>
                {rolloutFlags.data ? (
                  <div className="rounded-lg border p-2" style={{ borderColor: 'var(--border-subtle)' }}>
                    <div className="flex flex-wrap gap-2 mb-2">
                      {(rolloutFlags.data.supported_flags || []).map((flag) => <Badge key={flag}>{flag}</Badge>)}
                      {(rolloutFlags.data.supported_flags || []).length === 0 ? <Badge>No supported flags returned</Badge> : null}
                    </div>
                    <pre className="overflow-auto rounded border p-2 text-xs" style={{ borderColor: 'var(--border-subtle)', background: 'rgba(0,0,0,0.25)', color: 'var(--text-secondary)' }}>
{JSON.stringify(rolloutFlags.data.posture, null, 2)}
                    </pre>
                  </div>
                ) : (
                  <EmptyState title="No rollout flags data" detail="Admin access may be unavailable or backend route returned no data." />
                )}
              </div>
            </div>
          </Panel>
        </div>
      </div>
    </P0PageShell>
  );
}

function QueueSlaPanel({ snapshot }: { snapshot: ManagerVisibilitySnapshot }) {
  return (
    <div className="space-y-3">
      <div className="grid grid-cols-2 gap-2 md:grid-cols-4 text-sm">
        <Metric label="Total tickets" value={String(snapshot.queue_sla.total_tickets)} />
        <Metric label="AI decisions" value={String(snapshot.ai_audit.total_decisions)} />
        <Metric label="Pending HITL" value={String(snapshot.ai_audit.pending_hitl)} />
        <Metric label="Read-only rejects" value={String(snapshot.automation_audit.read_only_rejections)} />
      </div>
      {snapshot.queue_sla.by_queue.length === 0 ? (
        <EmptyState title="No queue rows" detail="Workflow inbox source is empty, so queue/SLA aggregation has no tickets to summarize." />
      ) : (
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr style={{ color: 'var(--text-muted)' }}>
                <th className="text-left py-2 pr-2">Queue</th>
                <th className="text-right py-2 px-2">Total</th>
                <th className="text-right py-2 px-2">Healthy</th>
                <th className="text-right py-2 px-2">At risk</th>
                <th className="text-right py-2 pl-2">Breached</th>
              </tr>
            </thead>
            <tbody>
              {snapshot.queue_sla.by_queue.map((row) => (
                <tr key={row.queue} className="border-t" style={{ borderColor: 'var(--border-subtle)' }}>
                  <td className="py-2 pr-2" style={{ color: 'var(--text-primary)' }}>{row.queue}</td>
                  <td className="py-2 px-2 text-right" style={{ color: 'var(--text-secondary)' }}>{row.total}</td>
                  <td className="py-2 px-2 text-right" style={{ color: '#86efac' }}>{row.healthy}</td>
                  <td className="py-2 px-2 text-right" style={{ color: '#fcd34d' }}>{row.at_risk}</td>
                  <td className="py-2 pl-2 text-right" style={{ color: '#fca5a5' }}>{row.breached}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      <div><MetaText>Generated at {new Date(snapshot.generated_at).toLocaleString()}.</MetaText></div>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border p-2" style={{ borderColor: 'var(--border-subtle)', background: 'rgba(255,255,255,0.015)' }}>
      <div className="text-[11px]" style={{ color: 'var(--text-muted)' }}>{label}</div>
      <div className="text-sm font-semibold" style={{ color: 'var(--text-primary)' }}>{value}</div>
    </div>
  );
}

function firstAdminError(errors: Array<string | null | undefined>): string | null {
  for (const error of errors) {
    if (!error) continue;
    if (/403|insufficient permissions|forbidden/i.test(error)) return error;
  }
  return null;
}
