export { PrepareContextService } from './context/prepare-context.js';

export {
  persistEvidencePack,
  getEvidencePack,
  persistTicketSSOT,
  persistTicketTextArtifact,
  getTicketTextArtifact,
  persistTicketContextAppendix,
  getTicketContextAppendix,
  persistItglueOrgSnapshot,
  getItglueOrgEnriched,
  upsertItglueOrgEnriched,
  persistNinjaOrgSnapshot,
  getNinjaOrgEnriched,
  upsertNinjaOrgEnriched,
} from './context/persistence.js';

export type {
  PrepareContextInput,
  TicketLike,
  TicketSSOT,
  TicketTextArtifact,
  TicketContextAppendix,
  ScopeMeta,
  ITGlueWanCandidate,
  ITGlueInfraCandidate,
  FacetContext,
  DeviceResolutionResult,
  ItglueEnrichedField,
  ItglueEnrichedPayload,
  NinjaEnrichedField,
  NinjaEnrichedPayload,
  FusionLink,
  FusionInference,
  FusionFieldCandidate,
  FusionFieldResolution,
  FusionAdjudicationOutput,
  AutotaskCreds,
  NinjaOneCreds,
  ITGlueCreds,
  HistoryCalibrationResult,
} from './context/prepare-context.types.js';
