// ─────────────────────────────────────────────────────────────
// Validate & Policy Service — Safety Gates & Policy Enforcement
// ─────────────────────────────────────────────────────────────

import type {
  DiagnosisOutput,
  ValidationOutput,
  Violation,
  EvidencePack,
} from '@playbook-brain/types';

export type GatingProfile = 'strict' | 'standard' | 'lenient';

interface CoverageThresholds {
  entity_coverage: number;
  tech_coverage: number;
  signal_coverage: number;
  asset_coverage: number;
}

export interface ValidationConfig {
  minHypothesisConfidence: number; // Minimum confidence to accept (default: 0.6)
  maxHighRiskActions: number; // Maximum high-risk actions allowed (default: 2)
  requireEvidencePerClaim: boolean; // Each hypothesis needs evidence (default: true)
  requireTestsPerAction: boolean; // Each hypothesis should have tests (default: true)
  profile: GatingProfile;
  coverageThresholds: CoverageThresholds;
}

const PROFILE_DEFAULTS: Record<GatingProfile, Pick<ValidationConfig, 'minHypothesisConfidence' | 'coverageThresholds'>> = {
  strict: {
    minHypothesisConfidence: 0.6,
    coverageThresholds: {
      entity_coverage: 0.6,
      tech_coverage: 0.6,
      signal_coverage: 0.6,
      asset_coverage: 0.6,
    },
  },
  standard: {
    minHypothesisConfidence: 0.45,
    coverageThresholds: {
      entity_coverage: 0.35,
      tech_coverage: 0.5,
      signal_coverage: 0,
      asset_coverage: 0,
    },
  },
  lenient: {
    minHypothesisConfidence: 0.35,
    coverageThresholds: {
      entity_coverage: 0.2,
      tech_coverage: 0.35,
      signal_coverage: 0,
      asset_coverage: 0,
    },
  },
};

export class ValidatePolicyService {
  private config: ValidationConfig;
  private profile: GatingProfile;

  constructor(config: Partial<ValidationConfig> = {}) {
    const profile = this.resolveProfile(config.profile);
    const defaults = PROFILE_DEFAULTS[profile];
    this.config = {
      minHypothesisConfidence: config.minHypothesisConfidence ?? defaults.minHypothesisConfidence,
      maxHighRiskActions: config.maxHighRiskActions ?? 2,
      requireEvidencePerClaim: config.requireEvidencePerClaim ?? true,
      requireTestsPerAction: config.requireTestsPerAction ?? true,
      profile,
      coverageThresholds: config.coverageThresholds ?? defaults.coverageThresholds,
    };
    this.profile = profile;
  }

  /**
   * Validate diagnosis output against safety policies
   */
  validate(
    diagnosis: DiagnosisOutput,
    pack: EvidencePack
  ): ValidationOutput {
    const violations: Violation[] = [];
    const requiredQuestions: Set<string> = new Set();
    const requiredFixes: Set<string> = new Set();
    const blockingReasons: string[] = [];
    const digest = pack.evidence_digest;

    const qualityGates = {
      cross_tenant_candidate_detected: Boolean(
        (digest?.rejected_evidence || pack.rejected_evidence || []).some(
          (item) =>
            item.reason === 'org_mismatch' ||
            item.reason === 'tenant_mismatch' ||
            item.reason === 'invalid_source_scope'
        )
      ),
      named_entity_unresolved: (pack.entity_resolution?.status || 'unresolved') !== 'resolved',
      domain_required_source_missing: this.hasDomainRequiredSourceMissing(pack),
      capability_verification_incomplete: this.isCapabilityVerificationIncomplete(pack),
      mandatory_ticket_fields_missing: this.hasMandatoryTicketFieldsMissing(pack),
    };
    const hasTicketActorContactHints = this.hasTicketActorContactHints(pack);

    const coverageScores = this.computeCoverageScores(pack);

    if (!diagnosis.top_hypotheses || diagnosis.top_hypotheses.length === 0) {
      violations.push({
        type: 'coherence',
        detail: 'No hypotheses generated by diagnosis step',
      });
      requiredFixes.add('Regenerate diagnosis with valid structured output');
      requiredQuestions.add('Collect additional data to support at least one hypothesis');
    }

    // ─── Check hypothesis quality ─────────────────────────────────
    const lowConfidenceHypotheses = diagnosis.top_hypotheses.filter(
      (h) => h.confidence < this.config.minHypothesisConfidence
    );

    if (lowConfidenceHypotheses.length > 0) {
      violations.push({
        type: 'coherence',
        detail: `${lowConfidenceHypotheses.length} hypothesis(es) below confidence threshold (${this.config.minHypothesisConfidence})`,
      });
      lowConfidenceHypotheses.forEach((h) => {
        requiredQuestions.add(`Validate hypothesis: ${h.hypothesis}`);
      });
    }

    // ─── Check evidence support ───────────────────────────────────
    if (this.config.requireEvidencePerClaim) {
      const unsupportedHypotheses = diagnosis.top_hypotheses.filter(
        (h) => !h.evidence || h.evidence.length === 0
      );

      if (unsupportedHypotheses.length > 0) {
        violations.push({
          type: 'no_evidence',
          detail: `${unsupportedHypotheses.length} hypothesis(es) lack supporting evidence`,
        });
        unsupportedHypotheses.forEach((h) => {
          requiredFixes.add(
            `Provide evidence for: "${h.hypothesis}"`
          );
        });
      }
    }

    // ─── Check test coverage ─────────────────────────────────────
    if (this.config.requireTestsPerAction) {
      const untestablePlan = diagnosis.top_hypotheses.filter(
        (h) => !h.tests || h.tests.length === 0
      );

      if (untestablePlan.length > 0) {
        violations.push({
          type: 'coherence',
          detail: `${untestablePlan.length} hypothesis(es) lack validation tests`,
        });
        untestablePlan.forEach((h) => {
          requiredFixes.add(
            `Add confirmation tests for: "${h.hypothesis}"`
          );
        });
      }
    }

    // ─── Check risk gates ─────────────────────────────────────────
    const highRiskActions = diagnosis.recommended_actions.filter(
      (a) => a.risk === 'high'
    );

    if (highRiskActions.length > this.config.maxHighRiskActions) {
      violations.push({
        type: 'risk_gate',
        detail: `Too many high-risk actions (${highRiskActions.length} > ${this.config.maxHighRiskActions}). Requires escalation.`,
      });
      requiredFixes.add(
        `Review and justify ${highRiskActions.length} high-risk actions`
      );
    }

    // ─── Check destructive action warnings ──────────────────────
    const destructivePatterns = [
      /delete|drop|truncate|format|wipe|erase|clear.*database/i,
      /restart.*production|reboot.*prod/i,
      /disable.*auth|disable.*firewall/i,
      /bypass.*policy|override.*security/i,
      /modify.*critical.*system|alter.*core/i,
    ];

    const destructiveActions = diagnosis.recommended_actions.filter((a) =>
      destructivePatterns.some((p) => p.test(a.action))
    );

    if (destructiveActions.length > 0 && pack.ticket.priority === 'Critical') {
      violations.push({
        type: 'risk_gate',
        detail: 'Destructive actions proposed on CRITICAL ticket',
      });
      destructiveActions.forEach((a) => {
        requiredFixes.add(
          `Critical ticket: Destructive action needs manual approval: "${a.action}"`
        );
      });
    }

    if (qualityGates.cross_tenant_candidate_detected) {
      violations.push({
        type: 'quality_gate',
        detail: 'cross_tenant_candidate_detected: evidence from divergent org/tenant was rejected',
      });
      requiredFixes.add('Collect equivalent evidence scoped to the ticket org');
      blockingReasons.push('cross_tenant_candidate_detected');
    }

    const shouldBlockNamedEntity =
      qualityGates.named_entity_unresolved &&
      (this.profile === 'strict' || !hasTicketActorContactHints);

    if (shouldBlockNamedEntity) {
      violations.push({
        type: 'quality_gate',
        detail: 'named_entity_unresolved: actor was not strongly resolved in org scope',
      });
      requiredQuestions.add(
        pack.entity_resolution?.disambiguation_question ||
          'Confirm exact affected actor (name/email/phone) inside ticket org scope'
      );
      blockingReasons.push('named_entity_unresolved');
    } else if (qualityGates.named_entity_unresolved) {
      requiredQuestions.add(
        pack.entity_resolution?.disambiguation_question ||
          'Confirm actor identity (name/email/phone) before closure'
      );
    }

    if (qualityGates.domain_required_source_missing) {
      violations.push({
        type: 'quality_gate',
        detail: 'domain_required_source_missing: required source for detected technology/domain was not consulted',
      });
      requiredFixes.add('Run directed retrieval for detected technology facets before approval');
      blockingReasons.push('domain_required_source_missing');
    }

    if (qualityGates.mandatory_ticket_fields_missing) {
      violations.push({
        type: 'quality_gate',
        detail: 'mandatory_ticket_fields_missing: canonical ticket block is missing required fields',
      });
      requiredFixes.add(
        'Re-run enrichment rounds until mandatory ticket fields (id/company/requester/affected/title/description) are confirmed'
      );
      blockingReasons.push('mandatory_ticket_fields_missing');
    }

    const shouldBlockCapabilityIncomplete =
      qualityGates.capability_verification_incomplete && this.profile === 'strict';
    if (shouldBlockCapabilityIncomplete) {
      violations.push({
        type: 'quality_gate',
        detail:
          'capability_verification_incomplete: capability ticket requires strong device match + official model spec confirmation',
      });
      requiredQuestions.add(
        'Provide device model/serial and confirm official vendor compatibility source URL'
      );
      blockingReasons.push('capability_verification_incomplete');
    } else if (qualityGates.capability_verification_incomplete) {
      requiredQuestions.add(
        'Capability check incomplete: collect device model/serial and official vendor spec URL before final closure'
      );
      requiredFixes.add(
        'Generate guided collection playbook only (avoid definitive compatibility conclusion)'
      );
    }

    const coverageThreshold = this.config.coverageThresholds;
    if (coverageScores.entity_coverage < coverageThreshold.entity_coverage) {
      violations.push({
        type: 'coverage_gate',
        detail: `entity_coverage below threshold (${coverageScores.entity_coverage.toFixed(2)} < ${coverageThreshold.entity_coverage})`,
      });
      requiredQuestions.add('Collect stronger actor evidence (exact name/email/phone) in org scope');
      blockingReasons.push('entity_coverage');
    }
    if (coverageScores.tech_coverage < coverageThreshold.tech_coverage) {
      violations.push({
        type: 'coverage_gate',
        detail: `tech_coverage below threshold (${coverageScores.tech_coverage.toFixed(2)} < ${coverageThreshold.tech_coverage})`,
      });
      requiredFixes.add('Consult technology-specific sources based on detected tech context');
      blockingReasons.push('tech_coverage');
    }
    if (coverageScores.signal_coverage < coverageThreshold.signal_coverage) {
      violations.push({
        type: 'coverage_gate',
        detail: `signal_coverage below threshold (${coverageScores.signal_coverage.toFixed(2)} < ${coverageThreshold.signal_coverage})`,
      });
      requiredQuestions.add('Collect at least one direct signal/alert supporting the diagnosis');
      blockingReasons.push('signal_coverage');
    }
    if (coverageScores.asset_coverage < coverageThreshold.asset_coverage) {
      violations.push({
        type: 'coverage_gate',
        detail: `asset_coverage below threshold (${coverageScores.asset_coverage.toFixed(2)} < ${coverageThreshold.asset_coverage})`,
      });
      requiredFixes.add('Collect asset/device capability evidence before final recommendation');
      blockingReasons.push('asset_coverage');
    }

    // ─── Check do_not_do compliance ───────────────────────────────
    const doNotDoList = diagnosis.do_not_do || [];
    if (doNotDoList.length === 0) {
      violations.push({
        type: 'coherence',
        detail: 'No safety constraints defined (do_not_do list is empty)',
      });
      requiredFixes.add('Define explicit safety constraints');
    }

    // ─── Check missing data severity ──────────────────────────────
    const criticalDataMissing = pack.missing_data?.filter(
      (m) => m.field === 'device' || m.field === 'user' || m.field === 'external_status'
    ) || [];

    if (
      criticalDataMissing.length > 0 &&
      (pack.ticket.priority === 'Critical' ||
        pack.ticket.priority === 'High')
    ) {
      violations.push({
        type: 'missing_checklist',
        detail: `Critical data missing on ${pack.ticket.priority} ticket:${criticalDataMissing.map((m) => ` ${m.field}`).join(',')}`,
      });
      criticalDataMissing.forEach((m) => {
        requiredQuestions.add(`Obtain missing critical data: ${m.field}`);
      });
    }

    // ─── Determine overall status ──────────────────────────────────
    let status: 'approved' | 'needs_more_info' | 'blocked' = 'approved';

    if (violations.some((v) => v.type === 'risk_gate')) {
      status = 'blocked';
    } else if (
      violations.some((v) => v.type === 'quality_gate' || v.type === 'coverage_gate')
    ) {
      status = 'needs_more_info';
    } else if (violations.some((v) => v.type === 'no_evidence')) {
      status = 'needs_more_info';
    } else if (violations.length > 0) {
      status = 'needs_more_info';
    }

    const hasRiskGate = violations.some((v) => v.type === 'risk_gate');
    const hasNoEvidence = violations.some((v) => v.type === 'no_evidence');
    const hasHardQualityStop =
      blockingReasons.includes('cross_tenant_candidate_detected') ||
      blockingReasons.includes('domain_required_source_missing') ||
      blockingReasons.includes('mandatory_ticket_fields_missing');

    const safeToGenerate =
      diagnosis.top_hypotheses.length > 0 &&
      !hasRiskGate &&
      !hasNoEvidence &&
      !hasHardQualityStop &&
      (this.profile === 'strict' ? status === 'approved' : true);

    return {
      status,
      violations,
      required_questions: Array.from(requiredQuestions),
      required_fixes: Array.from(requiredFixes),
      safe_to_generate_playbook: safeToGenerate,
      quality_gates: qualityGates,
      coverage_scores: coverageScores,
      blocking_reasons: [...new Set(blockingReasons.concat([`profile:${this.profile}`]))],
    };
  }

  private resolveProfile(profile?: GatingProfile): GatingProfile {
    if (profile) return profile;
    const envProfile = String(
      process.env.TRIAGE_GATING_PROFILE ||
      process.env.PIPELINE_GATING_PROFILE ||
      'standard'
    ).toLowerCase();
    if (envProfile === 'strict' || envProfile === 'lenient') {
      return envProfile;
    }
    return 'standard';
  }

  private hasTicketActorContactHints(pack: EvidencePack): boolean {
    const extracted = pack.entity_resolution?.extracted_entities;
    if (!extracted) return false;
    const hasPerson = extracted.person.length > 0;
    const hasDirectContact = extracted.email.length > 0 || extracted.phone.length > 0;
    return hasPerson && hasDirectContact;
  }

  private hasDomainRequiredSourceMissing(pack: EvidencePack): boolean {
    const tech = pack.evidence_digest?.tech_context_detected || [];
    if (!tech.length) return false;
    const consultedSources = new Set(
      Object.values(pack.evidence_digest?.sources_consulted_by_facet || {})
        .flatMap((v) => v || [])
        .map((source) => String(source).toLowerCase())
    );
    if (tech.includes('fortinet')) {
      const ok = consultedSources.has('itglue') && consultedSources.has('ninjaone');
      if (!ok) return true;
    }
    if (tech.includes('goto')) {
      const ok = consultedSources.has('itglue');
      if (!ok) return true;
    }
    if (tech.includes('vpn')) {
      const ok = consultedSources.has('itglue') && consultedSources.has('ninjaone');
      if (!ok) return true;
    }
    return false;
  }

  private hasMandatoryTicketFieldsMissing(pack: EvidencePack): boolean {
    const ticketSection = pack.iterative_enrichment?.sections?.ticket;
    if (!ticketSection) return false;

    const requiredFields = [
      ticketSection.ticket_id,
      ticketSection.company,
      ticketSection.requester_name,
      ticketSection.requester_email,
      ticketSection.affected_user_name,
      ticketSection.affected_user_email,
      ticketSection.created_at,
      ticketSection.title,
      ticketSection.description_clean,
    ];

    return requiredFields.some((field) => this.isMissingEnrichmentField(field));
  }

  private isMissingEnrichmentField(field: { value: unknown; status: string }): boolean {
    if (field.status === 'unknown' || field.status === 'conflict') return true;
    const value = field.value;
    if (value === null || value === undefined) return true;
    if (typeof value === 'string') {
      const normalized = value.trim().toLowerCase();
      return normalized.length === 0 || normalized === 'unknown';
    }
    if (Array.isArray(value)) {
      if (value.length === 0) return true;
      if (value.length === 1 && String(value[0] || '').trim().toLowerCase() === 'unknown') return true;
    }
    return false;
  }

  private isCapabilityVerificationIncomplete(pack: EvidencePack): boolean {
    const capability = pack.capability_verification || pack.evidence_digest?.capability_verification;
    if (!capability?.required) return false;
    return !capability.device_match_strong || !capability.model_spec_confirmed;
  }

  private computeCoverageScores(pack: EvidencePack) {
    const entityStatus = pack.entity_resolution?.status || 'unresolved';
    const entityCoverage =
      entityStatus === 'resolved'
        ? pack.entity_resolution?.resolved_actor?.confidence === 'medium'
          ? 0.7
          : 1
        : pack.entity_resolution?.actor_candidates?.length
          ? 0.45
          : this.hasTicketActorContactHints(pack)
            ? 0.35
            : 0;

    const techDetected = pack.evidence_digest?.tech_context_detected || [];
    const consultedSourcesCount = new Set(
      Object.values(pack.evidence_digest?.sources_consulted_by_facet || {}).flatMap((v) => v || [])
    ).size;
    const techCoverage =
      techDetected.length === 0
        ? 1
        : Math.min(1, consultedSourcesCount / Math.max(1, techDetected.length));

    const signalCoverage =
      pack.signals.length > 0
        ? 1
        : pack.docs.length > 0 || pack.related_cases.length > 0
          ? 0.35
          : 0;

    const capability = pack.capability_verification || pack.evidence_digest?.capability_verification;
    const assetCoverage =
      capability?.required
        ? Number(
            (
              (capability.device_match_strong ? 0.5 : 0) +
              (capability.model_spec_confirmed ? 0.5 : 0)
            ).toFixed(2)
          )
        : 1;

    return {
      entity_coverage: entityCoverage,
      tech_coverage: techCoverage,
      signal_coverage: signalCoverage,
      asset_coverage: assetCoverage,
    };
  }
}

/**
 * Validate diagnosis against policies
 */
export async function validateDiagnosis(
  diagnosis: DiagnosisOutput,
  pack: EvidencePack,
  config?: Partial<ValidationConfig>
): Promise<ValidationOutput> {
  const service = new ValidatePolicyService(config);
  return service.validate(diagnosis, pack);
}

/**
 * Quick safety check before proceeding to playbook generation
 */
export function isSafeToGenerate(validation: ValidationOutput): boolean {
  return (
    validation.safe_to_generate_playbook &&
    validation.status !== 'blocked' &&
    validation.violations.filter((v) => v.type === 'risk_gate').length === 0
  );
}
